import { ModalView } from "@/widgets/ModalView";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Header } from "@/widgets/Header";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen flex flex-col">
        <StoreProvider>
          <ModalView />
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
